### ISSUE TITLE
Loved the plugin

### ISSUE THREAD

**Issue by ghost** [fatmatto/ticli#1]
I'd like to propose some changes to the lib.

- Convert to ES6 (Babel/TypeScript) - I like TypeScript
- Writing unit testing

Do you've specific path for those 2 points so I can start contributing?

Thanks

**Comment by fatmatto** [comment]
My goal is to go full ES6 and start writing tests asap :) prs are welcome :) The 2 things can start independently but I did not have the time to choose a unit testing framework yet. I usually go with Mocha

**Comment by ghost** [comment]
Mocha is my choice also :smile: I'll watch the repo for tiny fixes so you can try those things yourself :wink:
